[project]
name = "athor-sketches"
version = "0.0.1"
description = "Contains the sketches used by my home and woodworking projects"
requires-python = ">=3.9, <3.13"

dependencies = [
  "cadquery",
  "CQ-editor",
]
